# Generated by Django 5.0.7 on 2024-07-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='parent_certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.certification'),
        ),
    ]
