# Generated by Django 5.0.7 on 2024-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certification_parent_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date_earned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
