# Generated by Django 5.0.7 on 2024-07-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_certification_parent_certification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
