# Generated by Django 5.0.7 on 2024-07-26 02:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_certification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='date_earned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='certification',
            name='parent_certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_certification_set', to='portfolio.certification'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
